---
apiVersion: v1
kind: Namespace
metadata:
  name: app-ns
  labels:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-ns
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 3000